import { auth } from "@/auth";
import Navbar from "../component/navbar";
import users from "@/app/model/users";

export const metadata = {
  title: "User DashBoard",
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const session = await auth();
  const { balance } = await users.findOne({_id: session?.user?.id});
  return (
    <>
      <Navbar balance={balance}/>
      {children}
    </>
  );
}
