import Navbar from "../component/navbar";

export const metadata = {
  title: "User DashBoard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
