import Footer from "../component/footer";
import Navbar from "../component/navbar";

export const metadata = {
  title: "Admin DashBoard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
