import { NextResponse } from "next/server";

export async function GET(params) {
  return NextResponse.json({
    roffer: {
      tel: "9999999999",
      operator: "Idea",
      records: [
        {
          rs: "449",
          desc: "Rs.449-Unlimited Local+National+Roaming Calls+100 SMS/D+114 GB @1.4GB/D DATA-82 Days",
        },
        {
          rs: "199",
          desc: "Rs.199-Unlimited Local+National+Roaming Calls+100SMS/Day+39 GB @1.4GB/DAY DATA-28 Days ",
        },
        {
          rs: "179",
          desc: "Rs.179-Unlimited Local+National+Roaming Calls+100SMS/Day+1GB-28 Days ",
        },
        { rs: "120", desc: "Aapka Khaas Offer! Rs 120 ke Rchg pe 120 ka TT" },
        { rs: "104", desc: "RC104-300 Local + STD Mobile Mins for 28 Days" },
        { rs: "62", desc: "Rs.62-Upto 5GB-15D-" },
        { rs: "45", desc: "Rs.45-1GB-28 Days-" },
        { rs: "29", desc: "Rs.29-250MB-28 Days-" },
        {
          rs: "0",
          desc: "Have Recharge karvu ekdam saral.MyIdea App par aakarshak Cashback offer ane discount coupons. Aajej Dial karo 12166",
        },
        {
          rs: "0",
          desc: "Aap na number ne Aadhar sathe link karvo jaruri che. Najik na store ni mulakat lo athwa Dial karo toll free 14546",
        },
        {
          rs: "0",
          desc: "Idea Ape che Validity addition suvidha jema aap Hal na UL Pack ni baki Validity nava UL ni validity ma Umerai jase.",
        },
        { rs: "0", desc: "Unlimited Song Change @2rs/day" },
      ],
      status: 1,
    },
    plans: {
      FULLTT: [
        {
          rs: "44",
          desc: "44 Full Talktime 2 Local airtel night min(1 day)",
          validity: "6 days",
          last_update: "26-01-2018",
        },
        {
          rs: "88",
          desc: "88 Full Talktime 2 local airtel night mins (1day)",
          validity: "13 days",
          last_update: "26-01-2018",
        },
        {
          rs: "109",
          desc: "109 Full Talktime 2 Local airtel night min(1 day)",
          validity: "15 days",
          last_update: "26-01-2018",
        },
        {
          rs: "120",
          desc: "120 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "210",
          desc: "210 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "230",
          desc: "230 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "250",
          desc: "250 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "300",
          desc: "300 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "306",
          desc: "306 Full Talktime Local & STD outgoing calls on National Roaming @60p/min",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "400",
          desc: "400 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "500",
          desc: "500 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "1000",
          desc: "1000 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "1500",
          desc: "1500 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "2000",
          desc: "2000 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "3000",
          desc: "3000 Full Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
      ],
      TOPUP: [
        {
          rs: "10",
          desc: "7.47 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "20",
          desc: "14.95 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "30",
          desc: "22.42 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "40",
          desc: "30.9 Talktime",
          validity: "999 days",
          last_update: "26-01-2018",
        },
        {
          rs: "50",
          desc: "39.37 Talktime ",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "60",
          desc: "47.85 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "70",
          desc: "56.32 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "80",
          desc: "64.8 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "90",
          desc: "73.27 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "100",
          desc: "81.75 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "110",
          desc: "90.22 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "130",
          desc: "125 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "140",
          desc: "115.64 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "150",
          desc: "140 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "180",
          desc: "170 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "190",
          desc: "158.02 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "200",
          desc: "190 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
        {
          rs: "490",
          desc: "415.25 Talktime",
          validity: "N/A",
          last_update: "26-01-2018",
        },
      ],
      "3G/4G": [
        {
          rs: "5",
          desc: "Rs 5= 30 MB 4G/3G/2G Data for 1 Days on all HS",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "14",
          desc: "90 MB 4G/3G/2G Data",
          validity: "3 days",
          last_update: "26-01-2018",
        },
        {
          rs: "15",
          desc: "30 MB 4G/3G/2G Data",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "25",
          desc: "170 MB 4G/3G/2G Data",
          validity: "5 days",
          last_update: "26-01-2018",
        },
        {
          rs: "29",
          desc: "150 MB 4G/3G/2G Data",
          validity: "30 days",
          last_update: "26-01-2018",
        },
        {
          rs: "43",
          desc: "1 GB 3G/4G Data",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "45",
          desc: "180 MB 2G/3G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "46",
          desc: "300 MB 4G/3G/2G Data",
          validity: "9 days",
          last_update: "26-01-2018",
        },
        {
          rs: "53",
          desc: "350 MB 4G/3G/2G Data",
          validity: "10 days",
          last_update: "26-01-2018",
        },
        {
          rs: "97",
          desc: "2 GB 2G/3G/4G data",
          validity: "5 days",
          last_update: "26-01-2018",
        },
        {
          rs: "145",
          desc: "580 MB 3G/4G Data",
          validity: "5 days",
          last_update: "26-01-2018",
        },
        {
          rs: "146",
          desc: "585 MB 3G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "175",
          desc: "2 GB 4G/3G/2G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "199",
          desc: "1.1 GB 4G/3G/2G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "248",
          desc: "3GB 4G/3G/2G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "255",
          desc: "4 GB 4G/3G/2G Data on 4G HS 15GB 28 D on Other HS",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "294",
          desc: "1 GB(3G) + 1 GB(4G) + 1 GB(night)",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "347",
          desc: "2.5 GB 3G + additional 5 GB 3G on Wifi",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "398",
          desc: "5 GB 4G/3G/2G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "992",
          desc: "10 GB 3G/4G Data",
          validity: "365 days",
          last_update: "26-01-2018",
        },
        {
          rs: "998",
          desc: "15 GB 4G/3G/2G Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
      ],
      "RATE CUTTER": [
        {
          rs: "6",
          desc: "Local mobile calls@30p/m. Daily 1st 60 local mobile sec @2p/s",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "8",
          desc: "STD mob calls@25p/m. Daily 1st 120s @2p/s",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "15",
          desc: "Local + STD A2A mobile calls @15p/m. Daily First 120 L+S A2A sec @1.8p/s",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "17",
          desc: "1500 Local+STD mobile sec",
          validity: "3 days",
          last_update: "26-01-2018",
        },
        {
          rs: "18",
          desc: "Local mobile calls@30p/m",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "27",
          desc: "Local mobile calls @25p/m",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "28",
          desc: "Local A2A calls @10p/m",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "31",
          desc: "Local + STD Mobile calls @1p/sec",
          validity: "56 days",
          last_update: "26-01-2018",
        },
        {
          rs: "34",
          desc: "Local+STD mob calls @30p/m",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "35",
          desc: "ISD - Russia @ Rs 6/min Gulf countries @12p/s US/Canada @3p/s Australia/Nepal/Nigeria/Qatar/UK @15p/s Oman @22p/s China @5p/s",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "36",
          desc: "2800 Loc+STD mobile secs",
          validity: "3 days",
          last_update: "26-01-2018",
        },
        {
          rs: "42",
          desc: "Nepal @Rs6/m and Bangladesh @3p/sec",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "51",
          desc: "Local Mobile calls @1p/sec",
          validity: "56 days",
          last_update: "26-01-2018",
        },
        {
          rs: "55",
          desc: "5000 Local+STD mob secs",
          validity: "2 days",
          last_update: "26-01-2018",
        },
        {
          rs: "65",
          desc: "5900 Local+STD mob secs",
          validity: "2 days",
          last_update: "26-01-2018",
        },
        {
          rs: "77",
          desc: "6800 Local+STD mob secs",
          validity: "2 days",
          last_update: "26-01-2018",
        },
        {
          rs: "95",
          desc: "7600 (Local+STD Mob Sec)",
          validity: "2 days",
          last_update: "26-01-2018",
        },
        {
          rs: "99",
          desc: "250 Local+STD mobile minutes",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "105",
          desc: "13000 Local+STD mob sec",
          validity: "28 days",
          last_update: "26-01-2018",
        },
      ],
      SMS: [
        {
          rs: "13",
          desc: "130 Local and National SMS",
          validity: "13 days",
          last_update: "26-01-2018",
        },
        {
          rs: "24",
          desc: "250 Local /STD SMS",
          validity: "15 days",
          last_update: "26-01-2018",
        },
        {
          rs: "47",
          desc: "500 Local and National SMS",
          validity: "28 days",
          last_update: "26-01-2018",
        },
      ],
      Romaing: [
        {
          rs: "26",
          desc: "National Roaming Benefit: Local & STD outgoing calls @60p/min",
          validity: "84 days",
          last_update: "26-01-2018",
        },
        {
          rs: "54",
          desc: "Home Tariff in National Roaming",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "309",
          desc: "Unlimited mobile+LL calls (Local+STD) in home and roam nerwork.",
          validity: "4 days",
          last_update: "26-01-2018",
        },
      ],
      COMBO: [
        {
          rs: "9",
          desc: "Unlimited all local+STD calls | 100mb data | 100 L/N SMS | UL Outgoing and Incoming roaming.T&C.",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "9",
          desc: "Unlimited all local+STD calls | 100mb data | 100 L/N SMS | UL Outgoing and Incoming roaming.T&C.",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "22",
          desc: "Unlimited A2A calls | 100 MB on 4G HS (50 MB on non 4G Data)",
          validity: "1 days",
          last_update: "26-01-2018",
        },
        {
          rs: "23",
          desc: "Unlimited local+STD calls | 150 MB data | 100 L/N SMS/day | UL Outgoing and Incoming roaming",
          validity: "2 days",
          last_update: "26-01-2018",
        },
        {
          rs: "59",
          desc: "Unlimited local + STD calls | 500 MB data | 100 L/N SMS per day + UL Outgoing and Incoming roaming. T&C apply.",
          validity: "7 days",
          last_update: "26-01-2018",
        },
        {
          rs: "92",
          desc: "Unlimited Airtel mobile local+STD calls + 100 Airtel to other network Loc+STD mob&LL mins | 50 MB 2G/3G/4G on Non 4G HS and 250 MB 2G/3G/4G on 4G HS",
          validity: "7 days",
          last_update: "26-01-2018",
        },
        {
          rs: "93",
          desc: "Unlimited Local + STD + Roaming calls | 100SMS/Day | 1GB 3G/4G data (on all handsets)",
          validity: "10 days",
          last_update: "26-01-2018",
        },
        {
          rs: "169",
          desc: "Unlimited All Local + STD call | 500 MB/day 4G/3G data on Airtel Partnered New 4G Handsets & 14 days for other handsets. T&C",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "179",
          desc: "Unlimited Local+STD calls | 1 GB data with roaming OG free | 100 SMS/DAY -all HS. T&C apply",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "197",
          desc: "Unlimited Local + STD + Roaming calls | 100 SMS/Day | 1.25 GB 3G/4G data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "249",
          desc: "FREE Local mobile calls | 1 GB on 4G handset & 50 MB on other handsets. T&C apply. 1 GB Happy Hours night data for 4G H/S & 50 MB for others(3AM to 5AM)",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "349",
          desc: "Unlimited all Local+STD Calls (non-commercial), free outgoing in National Roaming | 1.5GB/day 3G/4G Data | 100 Local+STD SMS/Day | on all handsets. T&C Apply",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "397",
          desc: "UL all Local & STD calls | 1 GB/day 3G/4G data + 1.25 GB 3G/4G data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "399",
          desc: "Unlimited local+STD calls | 1gb data/day | 100 L/N SMS per day | UL Outgoing and Incoming roaming.TnC apply.",
          validity: "56 days",
          last_update: "26-01-2018",
        },
        {
          rs: "448",
          desc: "Unlimited all Local+STD Calls (non-commercial), free outgoing in National Roaming | 1 GB/day 3G/4G Data | 100 Local+STD SMS/Day | on all handsets. T&C Apply",
          validity: "70 days",
          last_update: "26-01-2018",
        },
        {
          rs: "498",
          desc: "Unlimited Local+STD calls | 1 GB data/day with roaming OG free | 100 SMS/DAY -all HS. T&C apply",
          validity: "84 days",
          last_update: "26-01-2018",
        },
        {
          rs: "499",
          desc: "Unlimited Loc+STD all calls | 1.5 GB/Day 3G/4G data. T&C apply.",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "549",
          desc: "Unlimited all local+STD calls | 3gb data/day | 100 L/N SMS per day | UL Outgoing and Incoming roaming.T&C.",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "599",
          desc: "UL all L+S calls on all HS | 2 GB/Day Data on 4G H/S; 3 GB 28Days for Other H/S.",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "648",
          desc: "Unlimited Loc + STD all calls | 2.5 GB/Day 3G/4G data | T&C apply.",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "799",
          desc: "Unlimited all Local+STD Calls (non-commercial), free outgoing in National Roaming | 3.5GB/day 3G/4G Data | 100 Local+STD SMS/Day | on all handsets. T&C Apply",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "899",
          desc: "Unlimited Loc+STD all calls | 3.5 GB/Day 3G/4G data. T&C apply.",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "999",
          desc: "Unlimited all Local+STD Calls (non-commercial), free outgoing in National Roaming | 60 GB 3G/4G Data | 100 Local+STD SMS/Day | on all handsets. T&C Apply",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "1198",
          desc: "Unlimited Loc+STD calls | 5 GB/Day Data",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "1999",
          desc: "Unlimited all Local+STD Calls (non-commercial), free outgoing in National Roaming | 125 GB 3G/4G Data | 100 Local+STD SMS/Day | on all handsets. T&C Apply",
          validity: "180 days",
          last_update: "26-01-2018",
        },
        {
          rs: "3999",
          desc: "Unlimited all Local+STD Calls(non-commercial use),outgoing in National Roaming | 100 Local+STD SMS/Day | 300 GB 3G/4G,.All Handsets.T&C Apply",
          validity: "360 days",
          last_update: "26-01-2018",
        },
      ],
      FRC: [
        {
          rs: "11",
          desc: "All Local airtel calls @10 p/min | Applicable only for new subscribers as FRC/SRC",
          validity: "84 days",
          last_update: "26-01-2018",
        },
        {
          rs: "48",
          desc: "15 Talktime 100 MB 3G data (30 days) | L+S @10 P/SMS | All mobile calls (L+S) at 1.5p/sec & fixed line calls (L+S) at 2.5 p/s | Applicable only for new subscribers as FRC/SRC",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "51",
          desc: "25 Talktime 100 MB 4G/3G data (30 days) | 10p SMS (L+STD) | All mobile calls @1.5p/sec & fixed line calls @2.5 p/s | Applicable only for new subscribers as FRC/SRC",
          validity: "30 days",
          last_update: "26-01-2018",
        },
        {
          rs: "52",
          desc: "All Unlimited Local + STD calls in National Roaming (35 Days) | For 4G H/s and 4G SIM (T&C apply) | Applicable only on FRC 443",
          validity: "84 days",
          last_update: "26-01-2018",
        },
        {
          rs: "76",
          desc: "28 Talktime 175 MB 3G Data (30 days) | SMS (Local+STD) @10 p | All mobile calls @1.5p/sec & fixed line calls @2.5 p/s | Applicable only for new subscribers as FRC/SRC",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "81",
          desc: "46 Talktime 100 MB 3G data (30 days) | (Local+STD) @10 p/SMS | All (local+std) mobile calls at 1.5p/sec & fixed line (local+std) calls @2.5 p/s | Applicable only for new subscribers as FRC/SRC",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "143",
          desc: "Unlimited Local & STD Airtel calls | 2 GB data on 4G Handset with 4G SIM and 1 GB for others | T&C apply. | Applicable only for new subscribers as FRC/SRC",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "159",
          desc: "20 Talktime 500 MB(day) + 1 GB(night) 3G Data (30 days) | All local and STD mobile calls @1.5p/sec+10 p SMS (Local+STD) | Applicable only for new subscribers as FRC/SRC",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "178",
          desc: "Unlimited Local+STD calls | 1GB data with roaming OG free | 100SMS/DAY -all HS. T&C apply | Applicable only for new subscribers as FRC/SRC",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "193",
          desc: "4G handset+4G SIM: Unlimited Local+STD Airtel mobile + 150 A2M minutes, 2 GB data Other H/S:Unlimited Local+STD Airtel mobile + 150 A2M,1 GB Data, 28days,T&C apply. | Applicable only for new subscribers as FRC/SRC",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "343",
          desc: "Unlimited all Local+STD calls | 1 GB/day 3G/4G data. T&C apply. | Applicable only for new subscribers as FRC/SRC",
          validity: "28 days",
          last_update: "26-01-2018",
        },
        {
          rs: "401",
          desc: "200 Talktime 2 GB 4G/3G Data | SMS Local + National @10p/SMS | All mobile calls @1.5 p/s and fixed line calls @2.5 p/sec | Applicable only for new subscribers as FRC/SRC",
          validity: "90 days",
          last_update: "26-01-2018",
        },
        {
          rs: "443",
          desc: "Enjoy Unlimited Local+STD calls + 1GB data/day with roaming OG free +100sms/day -all HS. T&C apply | Applicable only for new subscribers as FRC/SRC",
          validity: "56 days",
          last_update: "26-01-2018",
        },
        {
          rs: "495",
          desc: "Enjoy Unlimited Local+STD calls + 1GB data/day with roaming OG free +100sms/day -all HS. T&C apply | Applicable only for new subscribers as FRC/SRC",
          validity: "70 days",
          last_update: "26-01-2018",
        },
        {
          rs: "559",
          desc: "Unlimited calls (local/std/roaming) | 1 GB/day data | 100 SMS/day on all handsets. | Applicable only for new subscribers as FRC/SRC",
          validity: "84 days",
          last_update: "26-01-2018",
        },
      ],
    },
  });
}
